package engineer.echo.easyapi.compiler;

import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

import java.io.IOException;
import java.util.HashMap;
import java.util.concurrent.ConcurrentHashMap;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;


public final class CompilerHelper {

    private static final String PACKAGE = "engineer.echo.easyapi.compiler";
    private static final String CLASS = "MetaInfo";

    public static boolean createMetaInfoFile(Filer filer, HashMap<String, String> meta) {
        TypeName typeName = ParameterizedTypeName.get(ConcurrentHashMap.class, String.class,String.class);
        // metaInfo
        FieldSpec metaInfo = FieldSpec.builder(typeName, "metaInfo")
                .addModifiers(Modifier.FINAL, Modifier.STATIC, Modifier.PRIVATE)
                .initializer("new $T()", ConcurrentHashMap.class)
                .build();

        // constructor
        MethodSpec.Builder constructorBuilder = MethodSpec.constructorBuilder();
        for (String key : meta.keySet()) {
            constructorBuilder.addStatement("$N.put($S, $S)", "metaInfo", key, meta.get(key));
        }
        MethodSpec constructor = constructorBuilder.build();

        // getClassById
        MethodSpec method = MethodSpec.methodBuilder("getClassById")
                .returns(String.class)
                .addParameter(String.class, "id")
                .addStatement(
                        "if ($N.containsKey($N)) return $N.get($N)",
                        "metaInfo", "id", "metaInfo", "id"
                )
                .addStatement("return null")
                .build();

        // class
        TypeSpec classType = TypeSpec.classBuilder(CLASS)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addMethod(constructor)
                .addField(metaInfo)
                .addMethod(method)
                .build();
        // file
        JavaFile javaFile = JavaFile.builder(PACKAGE, classType)
                .addFileComment("This codes are generated by EasyApi automatically. Do not modify!")
                .build();
        try {
            javaFile.writeTo(filer);
            return true;
        } catch (IOException e) {
            return false;
        }
    }
}
